GET http://localhost:3001/registry

###

POST http://localhost:3001/registry/new
Content-Type: application/json

{
    "date": "Sat April 2",
    "incidentLocation": "true",
    "alcoholInvolved": "false"
}

###

DELETE http://localhost:3001/registry/delete/${id}

###

PUT http://localhost:3001/registry/complete/${id}